### PR TITLE
Improvement to makeImage.sh

### PR DESCRIPTION
**Pull request by brianpow**
QEMU image size is guessed from tarball size instead of hard-coded to 1GB. 
Extract the tarball directly from image folder instead of copying to scratch folder and extracting.

### CODE REVIEW

**Comment by ddcc** [comment]
Why is the size computation using successive doubling from 8MB? How about e.g. `round_up(tar_sz + 8MB, 16MB)`, maybe with different constants?

**Comment by brianpow** [comment]
Because flash size usually in power of 2 (e.g. 8M, 16M, 32M, 64M, 128M .....). If the flash size is less than 8M, it does not have enough space for patching so I pick 8M as minimum

**Comment by ddcc** [comment]
Hmm, I understand that the actual flash chips may be manufactured with power-of-2 sizes, but since the filesystem is being unpacked into a QEMU virtual disk, does this make a difference? Is the main goal to reduce the file size of QEMU disk images, or something else?

**Comment by brianpow** [comment]
I can't think of any real world example currently for the advantage of having power-of-2 size over non-power-of-two size. But I am sure having 64MB (I believe majority of routers has 32M or less) over fixed 1GB matter while 48MB (i.e. `round_up(tar_sz + 8MB, 16MB)`) vs 64MB may not be a big deal to me/my SSD.  In case you feel `round_up(tar_sz + 8MB, 16MB)` is better, then feel free to change it.

**Comment by ddcc** [comment]
Ok, sounds good to me.

**Comment by megele** [comment]
I fail to recognize why setting 1GB as upper bound is a problem? What is the motivation for this change?
The generated images are sparse, so they take exactly as much space as there is useful data (which is almost always << 1GB)

**Comment by brianpow** [comment]
> I fail to recognize why setting 1GB as upper bound is a problem? What is the motivation for this change?
> The generated images are sparse, so they take exactly as much space as there is useful data (which is almost always << 1GB)

Just one quick example
If you have a root fs image that take more than 1GB, then it will failed before this pull.

**Pull request merged**
