### PR TITLE
check and rename /etc/securetty, code cleanup

### PR DESCRIPTION
**Pull request by brianpow**
check and rename /etc/securetty, 
code cleanup

### CODE REVIEW

**Comment by ddcc** [comment]
I'm not sure that this file should be automatically removed. It only matters for console access on this firmware, and the reason that it's in the README is to illustrate the process of mounting and unmounting the filesystem at the same time.

**Comment by brianpow** [comment]
Since fixImage script adds missing /etc/passwd, so I guess fixing /etc/securetty should be in the same purpose (i.e. allowing console access).

**Comment by AndrewFasano** [comment]
I think this logic might be broken - when the `fixImage.sh` script is run in a chroot by `makeImage.sh` it tries to use the `mv` binary inside the firmware filesystem (because of the chroot). If the firmware architecture doesn't match your host that's not going to work. If you used `cp` instead it would work since that's part of the busybox binary so it can be run without emulation.

**Comment by brianpow** [comment]
Would you check if your host busybox has 'mv' built-in ?

**Pull request merged**
